package com.chimpcentral.logger;

class BaseHTMLContent {

	static final String BASE_HTML = 
			"<!DOCTYPE html>\r\n"
			+ "<html lang=\"en\" style=\"height: 100%;\">\r\n"
			+ "    <head>\r\n"
			+ "        <title><!-- chimp-central-title --></title>\r\n"
			+ "        <meta charset=\"utf-8\">\r\n"
			+ "        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n"
			+ "        <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n"
			+ "        <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js\"></script>\r\n"
			+ "        <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n"
			+ "        \r\n"
			+ "        <script>\r\n"
			+ "            function displayTestLog(logId) {\r\n"
			+ "                Array.from(document.getElementsByClassName(\"test-log\")).forEach(function (element) {\r\n"
			+ "                    element.style.display = \"none\";\r\n"
			+ "                });\r\n"
			+ "                document.getElementById(logId).style.display = \"\";\r\n"
			+ "            }\r\n"
			+ "            function displayElement(elementId) {\r\n"
			+ "                var style = document.getElementById(elementId).style.display;\r\n"
			+ "                console.log(style);\r\n"
			+ "                if (style === \"none\") document.getElementById(elementId).style.display = \"\";\r\n"
			+ "                else document.getElementById(elementId).style.display = \"none\";\r\n"
			+ "            }\r\n"
			+ "        </script>\r\n"
			+ "\r\n"
			+ "        <style>\r\n"
			+ "            .containder-heading {\r\n"
			+ "                color: rgb(0, 0, 0);\r\n"
			+ "                font-weight: bold;\r\n"
			+ "            }  \r\n"
			+ "            .nav-button {\r\n"
			+ "                border: 0;\r\n"
			+ "                margin: 0;\r\n"
			+ "                background-color: black;\r\n"
			+ "                cursor: pointer;\r\n"
			+ "            }\r\n"
			+ "            .navigation-link {\r\n"
			+ "                border: 0;\r\n"
			+ "                margin: 0;\r\n"
			+ "                background-color: black;\r\n"
			+ "                cursor: pointer;\r\n"
			+ "                text-decoration: none;\r\n"
			+ "            }\r\n"
			+ "            .log-list {\r\n"
			+ "                border-top: grey;\r\n"
			+ "            }\r\n"
			+ "            .log-list-link {\r\n"
			+ "                color: rgb(121, 121, 121);\r\n"
			+ "                font-weight: bold;\r\n"
			+ "            }\r\n"
			+ "            .log-list-hr {\r\n"
			+ "                margin: 4px;\r\n"
			+ "            }\r\n"
			+ "            ul {\r\n"
			+ "                overflow-wrap: break-word;\r\n"
			+ "            }\r\n"
			+ "            table {\r\n"
			+ "                font-size: 12px;\r\n"
			+ "            }\r\n"
			+ "            td.warning {\r\n"
			+ "                color: red;\r\n"
			+ "            }\r\n"
			+ "            .collapsible {\r\n"
			+ "                padding-left: 10px;\r\n"
			+ "                padding-right: 10px;\r\n"
			+ "                font-size: 12px;\r\n"
			+ "            }\r\n"
			+ "            .collapsible-top {\r\n"
			+ "                background-color: lightgrey;\r\n"
			+ "                height: 35px;\r\n"
			+ "                padding-top: 10px;  \r\n"
			+ "                border-top-right-radius: 5px;\r\n"
			+ "                border-top-left-radius: 5px;\r\n"
			+ "                font-weight: bold;\r\n"
			+ "                cursor: pointer;\r\n"
			+ "            }\r\n"
			+ "            .collapsible-bottom {\r\n"
			+ "                background-color: #fafafa;\r\n"
			+ "                height: auto;\r\n"
			+ "                padding-top: 15px;\r\n"
			+ "                padding-bottom: 10px;\r\n"
			+ "                border-bottom-right-radius: 5px;\r\n"
			+ "                border-bottom-left-radius: 5px;\r\n"
			+ "            }\r\n"
			+ "        </style>\r\n"
			+ "\r\n"
			+ "    </head>\r\n"
			+ "\r\n"
			+ "    <body style=\"height: 100%;\">\r\n"
			+ "        \r\n"
			+ "        <div class=\"container-fluid\" style=\"width: 100%; height: 5px; background-color: black;\"></div>\r\n"
			+ "        \r\n"
			+ "        <div class=\"p-2 containder-heading text-center\">\r\n"
			+ "            <p style=\"font-size: 25px; margin: 5px;\"><!-- chimp-central-heading --></p>\r\n"
			+ "            <p style=\"font-size: 15px; margin: 5px;\"><!-- chimp-central-sub-heading --></p>\r\n"
			+ "        </div>\r\n"
			+ "        \r\n"
			+ "        <div class=\"container-fluid\" style=\"width: 100%; height: 5px; background-color: black;\"></div>\r\n"
			+ "\r\n"
			+ "        <div class=\"container-fluid\" style=\"width: 100%; padding: 0; height: 100%;\">\r\n"
			+ "            <div class=\"d-flex flex-row h-100\">\r\n"
			+ "                <div class=\"p-2 h-100\" style=\"background-color: rgb(0, 0, 0); width: 7%; height: 100%; overflow: auto;\">\r\n"
			+ "                    <br>\r\n"
			+ "                    <div class=\"d-flex\">\r\n"
			+ "                        <ul class=\"list-unstyled mx-auto text-center\">\r\n"
			+ "                            <li>\r\n"
			+ "                                <!-- chimp-central-logo-link -->\r\n"
			+ "                            </li>\r\n"
			+ "                            <br><br>\r\n"
			+ "                            <li>\r\n"
			+ "                                <!-- chimp-central-main-log-link -->\r\n"
			+ "                            </li>\r\n"
			+ "                            <br>\r\n"
			+ "                            <!-- chimp-central-additional-links -->\r\n"
			+ "                        </ul>\r\n"
			+ "                    </div>\r\n"
			+ "                </div>\r\n"
			+ "\r\n"
			+ "                <!-- chimp-central-log-list -->\r\n"
			+ "\r\n"
			+ "                <!-- chimp-central-log-container-start --><div class=\"p-2\" style=\"background-color: rgb(245, 245, 245); width: 100%\"><!-- chimp-central-log-container-end -->\r\n"
			+ "                    <div class=\"justify-content-center container\" style=\"width: 100%; height: 100%; overflow: auto;\">\r\n"
			+ "                        <table class=\"table table-responsive\" style=\"table-layout: fixed; word-wrap: break-word;\">\r\n"
			+ "                            <thead>\r\n"
			+ "                                <tr>\r\n"
			+ "                                    <th style=\"width: 10%;\">log info</th>\r\n"
			+ "                                    <th style=\"width: 15%;\">time</th>\r\n"
			+ "                                    <th style=\"width: 75%;\">message</th>\r\n"
			+ "                                </tr>\r\n"
			+ "                            </thead>\r\n"
			+ "                            \r\n"
			+ "                            <!-- chimp-central-log-table-body -->\r\n"
			+ "\r\n"
			+ "                        </table>\r\n"
			+ "                    </div>\r\n"
			+ "                </div>\r\n"
			+ "            </div>\r\n"
			+ "        </div>\r\n"
			+ "    </body>\r\n"
			+ "</html>\r\n"
			+ "";
	
	static final String LOGO_LINK = 
			"<a class=\"nav-button\" href=\"<!-- chimp-central-logo-link-href -->\" target=\"_blank\">\r\n"
			+ "    <img style=\"width: 30px;\" src=\"<!-- chimp-central-logo-link-src-url -->\"/>\r\n"
			+ "</a>";
	
	static final String MAIN_LOG_TEXT_LINK = 
			"<a class=\"navigation-link\" onclick=\"displayTestLog('main-logs')\">main log</a> ";
	
	static final String MAIN_LOG_IMAGE_LINK =
			"<a class=\"nav-button\" onclick=\"displayTestLog('main-logs')\">\r\n"
			+ "    <img style=\"width: 30px;\" src=\"<!-- chimp-central-main-log-link-src-url -->\"/>\r\n"
			+ "</a>";
	
	static final String ADDITIONAL_TEXT_LINK =
			"<li>\r\n"
			+ "    <a class=\"navigation-link\" href=\"<!-- chimp-central-additional-link-href -->\" target=\"_blank\"><!-- chimp-central-additional-link-name --></a>\r\n"
			+ "</li>\r\n"
			+ "<br>";
	
	static final String ADDITONAL_IMAGE_LINK =
			"<li>\r\n"
			+ "    <a class=\"nav-button\" href=\"<!-- chimp-central-additional-link-href -->\" target=\"_blank\">\r\n"
			+ "        <img style=\"width: 30px;\" src=\"<!-- chimp-central-additional-link-src-url -->\">\r\n"
			+ "    </a>\r\n"
			+ "</li>\r\n"
			+ "<br>\r\n"
			+ "";
	
	static final String LOG_LIST_CONTAINER_HTML =
			"<div class=\"p-2\" style=\"background-color: rgb(245, 245, 245); width: 25%; \">\r\n"
			+ "    <div style=\"position: absolute; height: 100%; overflow: auto; width: 20%;\">\r\n"
			+ "        <ul class=\"list-unstyled sticky-top\">\r\n"
			+ "            <!-- chimp-central-log-list-item -->\r\n"
			+ "        </ul>\r\n"
			+ "    </div>\r\n"
			+ "</div>";
	
	static final String LOG_LIST_ITEM_HTML = 
			"<li class=\"log-list\">\r\n"
			+ "    <a class=\"nav-link log-list-link\" onclick=\"displayTestLog('<!-- chimp-central-log-table-body-id -->')\"><!-- chimp-central-log-list-item-name --></a>\r\n"
			+ "</li>\r\n"
			+ "<hr class=\"log-list-hr\">\r\n"
			+ "<!-- chimp-central-log-list-item -->";
	
	static final String LOG_CONTAINER_WITHOUT_LOG_LIST_HTML = 
			"<!-- chimp-central-log-container-start --><div class=\"p-2\" style=\"background-color: rgb(245, 245, 245); width: 100%\"><!-- chimp-central-log-container-end -->";
	
	static final String LOG_CONTAINER_WITH_LOGLIST_HTML =
			"<!-- chimp-central-log-container-start --><div class=\"p-2\" style=\"background-color: rgb(245, 245, 245); width: 80%\"><!-- chimp-central-log-container-end -->";
	
	static final String LOG_TABLE_BODY_HTML = 
			"<tbody id=\"<!-- chimp-central-log-table-body-id -->\" class=\"test-log\" style=\"display: none;\">\r\n"
			+ "    <!-- chimp-central-log-table-row -->\r\n"
			+ "</tbody>\r\n"
			+ "<!-- chimp-central-log-table-body -->";
	
	static final String LOG_COLLAPSIBLE_HTML =
			"<div class=\"collapsible collapsible-top\" onclick=\"displayElement('<!-- chimp-central-log-collapsible-bottom-id -->')\">\r\n"
			+ "    <p><!-- chimp-central-log-collapsible-top-text --></p>\r\n"
			+ "</div>\r\n"
			+ "<div id=\"<!-- chimp-central-log-collapsible-bottom-id -->\" class=\"collapsible collapsible-bottom\" style=\"display: none;\">\r\n"
			+ "    <p><!-- chimp-central-log-collapsible-bottom-text --></p>\r\n"
			+ "</div>";
}
